# Generated by Django 3.1.7 on 2021-08-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='receiverID',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='senderID',
        ),
    ]
