# Generated by Django 3.1.7 on 2021-08-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FleaMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=30)),
                ('category', models.TextField(choices=[('디지털기기', '디지털기기'), ('생활가전', '생활가전'), ('가구/인테리어', '가구/인테리어'), ('유아동', '유아동'), ('생활/가공식품', '생활/가공식품'), ('스포츠/레저', '스포트/레저'), ('여성잡회/의류', '여성잡화/의류'), ('남성잡화/의류', '남성잡화/의류'), ('뷰티/미용', '뷰티/미용'), ('도서/티켓/음반', '도서/티켓/음반'), ('기타 중고물품', '기타 중고물품')])),
                ('pub_date', models.DateTimeField()),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='fleaMarket/')),
            ],
        ),
    ]
