# Generated by Django 3.1.7 on 2021-08-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleaMarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleamarket',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
